theme:
        default: style-light
site:
        title: Cetuxi's Home
favicon:
  logo: cat.svg
  icon16: cat.svg
  icon32: cat.svg
  apple_touch_icon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！

assets:
  third_party_provider: https://npm.elemecdn.com
user:
        name: Cetuxi
        first_name: come
        last_name: Wel
        email: y1079497319@outlook.com
        avatar: images/avatar.jpg
        domain: https://ygwlg.github.io/
        describe: Cetuxi's home
top_bars:
  - title: home
    url: /
  - title: archives
    url: /archives/
    noswup: true
  - title: about
    url: /about/
    noswup: true

sidebar:
        typed_text_prefix: "NO"
        typed_text: ["TIME", "MONEY", "WORRIES"]
